openapi: 3.0.3
info:
  title: Transfer API
  description: Transfer API - Desafio PicPay
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Transfer
  - name: User
paths:
  /transfer:
    post:
      tags:
        - Transfer
      summary: Lista todas as transferências
      operationId: createTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Cria uma nova transferência
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '4XX':
            description: Erro na requisição
            content:
              application/json:
                schema:
                    $ref: '#/components/schemas/Error'

  /user:
    post:
      tags:
        - User
      summary: Cria um novo usuário
      operationId: createUser
      responses:
        '200':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    TransferRequest:
      type: object
      properties:
        from_id:
          type: integer
          format: int64
        to_id:
          type: integer
          format: int64
        value:
          type: number
          format: double

    TransferResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        from:
          $ref: '#/components/schemas/User'
        to:
          $ref: '#/components/schemas/User'
        value:
          type: number
          format: double
        created_at:
          type: string
          format: date-time

    User:
        type: object
        properties:
          user_id:
            type: integer
            format: int64
          full_name:
            type: string
          email:
            type: string
          cpf/cnpj:
            type: string

    Error:
        type: object
        properties:
          error:
            type: string
          error_description:
            type: string
