openapi: 3.0.3
info:
  title: Transfer API
  description: Transfer API - Desafio PicPay
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Transfer
  - name: User
  - name: Account
paths:
  /account:
    post:
      tags:
        - Account
      summary: Cria uma nova conta
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Conta criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '4XX':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /transfer:
    post:
      tags:
        - Transfer
      summary: Lista todas as transferências
      operationId: createTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Cria uma nova transferência
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '4XX':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user:
    post:
      tags:
        - User
      summary: Cria um novo usuário
      operationId: createUser
      responses:
        '200':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    TransferRequest:
      type: object
      properties:
        from_acc_id:
          type: integer
          format: long
        to_acc_id:
          type: integer
          format: long
        value:
          type: number
          format: double

    TransferResponse:
      type: object
      properties:
        transfer_id:
          type: integer
          format: int64
        from:
          $ref: '#/components/schemas/Account'
        to:
          $ref: '#/components/schemas/Account'
        value:
          type: number
          format: double

    User:
      type: object
      properties:
        user_id:
          type: integer
          format: long
        full_name:
          type: string
        email:
          type: string
        cpf:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Account:
      type: object
      properties:
        acc_id:
          type: integer
          format: long
        user_id:
          type: integer
          format: long

    Error:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string